version: '3.6'  
services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=eVoting
    ports:
      - "8001:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
